import React,{useCallback,useEffect,useState} from 'react';
import {useSelector} from 'react-redux'; import {Navigate} from 'react-router-dom';
import '../assets/CSS/AdminDashboard.css'; import IncidentWorkflow from '../components/IncidentWorkflow';
const api=async(path,options={})=>{const token=localStorage.getItem('token');const headers={'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d;};
const BarList=({title,data})=><div className="chart-card"><h3>{title}</h3>{Object.entries(data||{}).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=><div className="bar-row" key={k}><span>{k}</span><div><i style={{width:`${Math.max(5,Math.min(100,(v/Math.max(...Object.values(data||{x:1})))*100))}%`}}></i></div><b>{v}</b></div>)}</div>;
export default function AdminDashboard(){
 const isAdmin=useSelector(s=>s.roleState.isAdmin),loggedIn=useSelector(s=>s.roleState.loggedIn); const [summary,setSummary]=useState(null),[dashboard,setDashboard]=useState(null),[audit,setAudit]=useState([]),[active,setActive]=useState('overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[expandedId,setExpandedId]=useState(null);
 const [announcement,setAnnouncement]=useState({Title:'',Content:'',Urgency:'medium',CommunityID:'',ExpiresAt:''}); const [task,setTask]=useState({Description:'',AssignedTo:'',IncidentID:''}); const [allocation,setAllocation]=useState({ResourceID:'',IncidentID:'',Quantity:''});
 const load=useCallback(async()=>{try{setError('');const [s,d,a]=await Promise.all([api('/api/admin'),api('/api/dashboard'),api('/api/admin/audit')]);setSummary(s);setDashboard(d);setAudit(a.logs||[]);}catch(e){setError(e.message);}},[]); useEffect(()=>{if(isAdmin)load();},[isAdmin,load]);
 if(!loggedIn)return <Navigate to="/auth/login" replace/>; if(!isAdmin)return <div className="admin-page"><div className="admin-card"><h2>Admin access required</h2><p>Your account does not have administrator permissions.</p></div></div>;
 const action=async(fn)=>{try{setBusy(true);await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const publish=e=>{e.preventDefault();action(async()=>{await api('/api/announcements',{method:'POST',body:JSON.stringify(announcement)});setAnnouncement({Title:'',Content:'',Urgency:'medium',CommunityID:'',ExpiresAt:''});});};
 const assign=e=>{e.preventDefault();action(async()=>{await api('/api/tasks',{method:'POST',body:JSON.stringify(task)});setTask({Description:'',AssignedTo:'',IncidentID:''});});};
 const allocate=e=>{e.preventDefault();action(async()=>{await api(`/api/resources/${allocation.ResourceID}/allocate`,{method:'POST',body:JSON.stringify({IncidentID:Number(allocation.IncidentID),Quantity:Number(allocation.Quantity)})});setAllocation({ResourceID:'',IncidentID:'',Quantity:''});});};
 const incidentAction=(i,a,p={})=>action(async()=>{const id=i.IncidentID;if(a==='verify')await api(`/incident/${id}/verify`,{method:'POST',body:JSON.stringify(p)});else if(a==='reject')await api(`/incident/${id}/reject`,{method:'POST',body:JSON.stringify(p)});else if(a==='assign')await api(`/incident/${id}/assign`,{method:'POST',body:JSON.stringify(p)});else if(a==='status')await api(`/incident/${id}/status`,{method:'PATCH',body:JSON.stringify(p)});else if(a==='note')await api(`/incident/${id}/notes`,{method:'POST',body:JSON.stringify(p)});});
 const updateUser=(u,patch)=>action(async()=>{await api(`/api/admin/users/${u.UserID}`,{method:'PATCH',body:JSON.stringify(patch)});});
 const stats=dashboard?.stats||{}; const charts=dashboard?.charts||{};
 return <div className="admin-page"><aside className="admin-sidebar"><div className="admin-brand"><strong>🛡 Suraksha Setu</strong><span>Admin Control Centre</span></div>{['overview','incidents','announcements','volunteers','resources','users','communities','audit'].map(item=><button key={item} className={active===item?'active':''} onClick={()=>setActive(item)}>{({overview:'📊',incidents:'🚨',announcements:'📢',volunteers:'👥',resources:'📦',users:'👤',communities:'🏘️',audit:'🧾'})[item]} {item[0].toUpperCase()+item.slice(1)}</button>)}</aside>
 <main className="admin-main"><div className="admin-top"><div><h1>Admin Dashboard</h1><p>Live disaster-response control centre for India.</p></div><span className="admin-badge">ADMIN</span></div>{error&&<div className="admin-error">{error}</div>}{busy&&<div className="admin-loading">Saving changes…</div>}
 {(active==='overview'||active==='incidents')&&<section><div className="admin-stats">{[["Active Incidents",stats.activeIncidents||0],["Critical",stats.criticalIncidents||0],["People Affected",stats.peopleAffected||0],["Volunteers",stats.volunteers||0],["Communities",stats.communities||0],["Resource Units",stats.resourceUnits||0],["Help Centres",stats.centers||0]].map(([l,v])=><div className="admin-stat" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>{active==='overview'&&<div className="charts-grid"><BarList title="Incidents by type" data={charts.byType}/><BarList title="Incidents by state" data={charts.byState}/><BarList title="Incident status" data={charts.byStatus}/></div>}<div className="admin-card"><h2>Incident Management</h2><p>Reported → Verified → Team assigned → Response started → Resolved</p><div className="incident-list">{(dashboard?.incidents||[]).map(i=><div className="incident-row" key={i.IncidentID}><button type="button" className="incident-summary" onClick={()=>setExpandedId(expandedId===i.IncidentID?null:i.IncidentID)}><span>#{i.IncidentID} · {i.IncidentType}</span><span className={`priority-badge priority-${(i.Priority||'medium').toLowerCase()}`}>{i.Priority||i.Urgency}</span><span>{i.Status}</span><span className="muted">{i.IncidentLocation||`Location ${i.LocationID}`}</span></button>{expandedId===i.IncidentID&&<IncidentWorkflow incident={i} canManage users={summary?.users||[]} onAction={(a,p)=>incidentAction(i,a,p)}/>}</div>)}</div></div></section>}
 {active==='announcements'&&<section className="admin-card"><h2>Raise an Announcement</h2><form className="admin-form" onSubmit={publish}><label>Title<input value={announcement.Title} onChange={e=>setAnnouncement({...announcement,Title:e.target.value})} placeholder="Heavy rainfall warning"/></label><label>Message<textarea value={announcement.Content} onChange={e=>setAnnouncement({...announcement,Content:e.target.value})} required placeholder="Write an official disaster-response announcement…"/></label><div className="form-grid"><label>Priority<select value={announcement.Urgency} onChange={e=>setAnnouncement({...announcement,Urgency:e.target.value})}><option>low</option><option>medium</option><option>high</option></select></label><label>Community ID (optional)<input type="number" value={announcement.CommunityID} onChange={e=>setAnnouncement({...announcement,CommunityID:e.target.value})} placeholder="Blank = all communities"/></label><label>Expires at<input type="datetime-local" value={announcement.ExpiresAt} onChange={e=>setAnnouncement({...announcement,ExpiresAt:e.target.value})}/></label></div><button>📢 Publish Announcement</button></form><h3>Recent announcements</h3>{(dashboard?.announcements||[]).map(a=><div className="admin-notice" key={a.AnnouncementID}><b>{a.Urgency?.toUpperCase()}</b><strong>{a.Title}</strong><p>{a.Content}</p><small>{new Date(a.CreationDate).toLocaleString('en-IN')}</small></div>)}</section>}
 {active==='volunteers'&&<section className="admin-card"><h2>Volunteer Tasks</h2><form className="admin-form admin-inline" onSubmit={assign}><input value={task.Description} onChange={e=>setTask({...task,Description:e.target.value})} placeholder="Task description" required/><input type="number" value={task.AssignedTo} onChange={e=>setTask({...task,AssignedTo:e.target.value})} placeholder="Volunteer User ID" required/><input type="number" value={task.IncidentID} onChange={e=>setTask({...task,IncidentID:e.target.value})} placeholder="Incident ID" required/><button>Assign Task</button></form><div className="admin-table-wrap"><table><thead><tr><th>Task</th><th>Volunteer</th><th>Incident</th><th>Status</th></tr></thead><tbody>{(summary?.tasks||[]).map(t=><tr key={t.TaskID}><td>{t.Description}</td><td>{t.AssignedTo}</td><td>#{t.IncidentID}</td><td>{t.Status}</td></tr>)}</tbody></table></div></section>}
 {active==='resources'&&<section className="admin-card"><h2>Resource Inventory & Allocation</h2><div className="admin-table-wrap"><table><thead><tr><th>Resource</th><th>Quantity</th><th>Unit</th><th>Status</th></tr></thead><tbody>{(summary?.resources||[]).map(r=><tr key={r.ResourceID}><td>{r.Name}</td><td>{r.Quantity}</td><td>{r.QuantityType}</td><td>{r.Status}</td></tr>)}</tbody></table></div><form className="admin-form admin-inline" onSubmit={allocate}><select value={allocation.ResourceID} onChange={e=>setAllocation({...allocation,ResourceID:e.target.value})} required><option value="">Select resource</option>{(summary?.resources||[]).map(r=><option key={r.ResourceID} value={r.ResourceID}>{r.Name} ({r.Quantity} {r.QuantityType})</option>)}</select><input type="number" value={allocation.IncidentID} onChange={e=>setAllocation({...allocation,IncidentID:e.target.value})} placeholder="Incident ID" required/><input type="number" min="1" value={allocation.Quantity} onChange={e=>setAllocation({...allocation,Quantity:e.target.value})} placeholder="Quantity" required/><button>Allocate</button></form><h3>Recent allocations</h3><div className="admin-table-wrap"><table><thead><tr><th>Allocation</th><th>Resource</th><th>Incident</th><th>Quantity</th><th>Date</th></tr></thead><tbody>{(summary?.allocations||[]).map(a=><tr key={a.AllocationID}><td>#{a.AllocationID}</td><td>#{a.ResourceID}</td><td>#{a.IncidentID}</td><td>{a.Quantity}</td><td>{new Date(a.AllocatedAt).toLocaleString('en-IN')}</td></tr>)}</tbody></table></div></section>}
 {active==='users'&&<section className="admin-card"><h2>User Management</h2><div className="admin-table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Role</th><th>Active</th><th>Availability</th><th>Action</th></tr></thead><tbody>{(summary?.users||[]).map(u=><tr key={u.UserID}><td>{u.UserID}</td><td>{u.Name}</td><td>{u.Email}</td><td><select value={u.UserType?.[0]||'affected'} onChange={e=>updateUser(u,{UserType:[e.target.value]})}><option>affected</option><option>donor</option><option>volunteer</option><option>responder</option><option>admin</option></select></td><td>{u.Active===false?'No':'Yes'}</td><td>{u.Available?'Available':'Unavailable'}</td><td><button className="table-action" onClick={()=>updateUser(u,{Active:u.Active===false})}>{u.Active===false?'Enable':'Disable'}</button></td></tr>)}</tbody></table></div></section>}
 {active==='communities'&&<section className="admin-card"><h2>Communities</h2><div className="admin-table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Members</th><th>Leader</th></tr></thead><tbody>{(dashboard?.communities||[]).map(c=><tr key={c.ComID}><td>{c.ComID}</td><td>{c.Name}</td><td>{c.Users?.length||0}</td><td>{c.Leader}</td></tr>)}</tbody></table></div></section>}
 {active==='audit'&&<section className="admin-card"><h2>Audit Log</h2><div className="admin-table-wrap"><table><thead><tr><th>Date</th><th>User</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{audit.map(x=><tr key={x.AuditID}><td>{new Date(x.CreatedAt).toLocaleString('en-IN')}</td><td>#{x.UserID}</td><td>{x.Action}</td><td>{x.EntityType} #{x.EntityID||'-'}</td><td>{x.Details}</td></tr>)}</tbody></table></div></section>}
 </main></div>;
}
