const express=require('express');
const router=express.Router();
const auth=require('../middleware/auth');
const role=require('../middleware/role');
const op=require('../controllers/Operations');
router.get('/dashboard',op.dashboard);
router.get('/communities',op.communities);
router.get('/locations',op.locations);
router.get('/resources',op.listResources);
router.get('/donations',op.donations);
router.get('/tasks',auth,op.tasks);
router.get('/notifications',auth,op.notifications);
router.post('/locations',auth,role('admin','responder'),op.createLocation);
router.patch('/resources/:id',auth,role('admin','responder'),op.updateResource);
router.post('/resources/:id/allocate',auth,role('admin','responder'),op.allocateResource);
router.post('/tasks',auth,role('admin','responder'),op.createTask);
router.patch('/tasks/:id',auth,op.updateTask);
router.post('/notifications/:id/read',auth,op.readNotification);
router.post('/sos',auth,op.sos);
router.post('/donate',auth,op.donate);
router.get('/admin',auth,role('admin'),op.adminSummary);
router.get('/team-users',auth,role('admin','responder'),op.teamUsers);
router.post('/communities/:id/join',auth,op.joinCommunity);
router.post('/communities/:id/leave',auth,op.leaveCommunity);
router.post('/communities/:id/messages',auth,op.postMessage);
router.post('/announcements',auth,role('admin','responder'),op.postAnnouncement);
module.exports=router;
