import React,{useEffect,useMemo,useState} from 'react';
import {MapContainer,TileLayer,Marker,Popup} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import '../assets/CSS/OperationsDashboard.css';
import IncidentWorkflow from './IncidentWorkflow';
import iconRetinaUrl from 'leaflet/dist/images/marker-icon-2x.png';
import iconUrl from 'leaflet/dist/images/marker-icon.png';
import shadowUrl from 'leaflet/dist/images/marker-shadow.png';
delete L.Icon.Default.prototype._getIconUrl; L.Icon.Default.mergeOptions({iconRetinaUrl,iconUrl,shadowUrl});
const center=[22.5937,78.9629],bounds=[[6,68],[37.5,97.5]];
const api=async(path,options={})=>{const token=localStorage.getItem('token');const headers={'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;};
const emptyIncident={IncidentType:'Flood',Description:'',Priority:'Medium',Latitude:'21.2514',Longitude:'81.6296',Address:'',ApproximateaffectedCount:0};
export default function OperationsDashboard({adminOnly=false}){
 const [data,setData]=useState(null),[locations,setLocations]=useState([]),[tasks,setTasks]=useState([]),[resources,setResources]=useState([]),[notifs,setNotifs]=useState([]),[teamUsers,setTeamUsers]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview'),[expandedId,setExpandedId]=useState(null);
 const [incident,setIncident]=useState(emptyIncident),[announcement,setAnnouncement]=useState({Content:'',Urgency:'medium',CommunityID:''}),[task,setTask]=useState({Description:'',AssignedTo:'',IncidentID:''}),[donation,setDonation]=useState({Amount:'',ResourceID:'1'}),[allocation,setAllocation]=useState({ResourceID:'',IncidentID:'',Quantity:''});
 const user=useMemo(()=>{try{return JSON.parse(localStorage.getItem('user')||'null')}catch{return null}},[]),isAdmin=user?.UserType?.includes('admin'),isResponder=user?.UserType?.includes('responder'),canManage=isAdmin||isResponder;
 const load=async()=>{try{setError('');const [d,l,r,t]=await Promise.all([api('/api/dashboard'),api('/api/locations'),api('/api/resources'),api('/api/tasks')]);setData(d);setLocations(l.locations||[]);setResources(r.resources||[]);setTasks(t.tasks||[]);if(user){const n=await api('/api/notifications');setNotifs(n.notifications||[])}if(canManage){try{const tu=await api('/api/team-users');setTeamUsers(tu.users||[])}catch{setTeamUsers([])}}}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const submitIncident=async e=>{e.preventDefault();if(!localStorage.getItem('token'))return setError('Please log in before reporting an incident.');setBusy(true);try{const loc=await api('/api/locations',{method:'POST',body:JSON.stringify({Latitude:Number(incident.Latitude),Longitude:Number(incident.Longitude),Address:incident.Address||'Selected location in India'})});await api('/incident/create',{method:'POST',body:JSON.stringify({LocationID:loc.location.LocationID,IncidentType:incident.IncidentType,Description:incident.Description,Priority:incident.Priority,ApproximateaffectedCount:Number(incident.ApproximateaffectedCount),Latitude:Number(incident.Latitude),Longitude:Number(incident.Longitude),IncidentLocation:incident.Address})});setIncident(emptyIncident);await load();setTab('incidents');setError('Incident reported successfully.');}catch(e){setError(e.message)}finally{setBusy(false)}};
 const sos=async()=>{if(!localStorage.getItem('token'))return setError('Login is required for SOS.');if(!navigator.geolocation)return setError('Geolocation is not available in this browser.');setBusy(true);navigator.geolocation.getCurrentPosition(async p=>{try{const result=await api('/incident/sos',{method:'POST',body:JSON.stringify({Latitude:p.coords.latitude,Longitude:p.coords.longitude})});await load();setError(`SOS ${result.SOSID||''} created. ${result.nearestCenter?.Name||'Response team notified.'}`)}catch(e){setError(e.message)}finally{setBusy(false)}},()=>{setError('Location permission was denied.');setBusy(false)},{enableHighAccuracy:true,timeout:10000})};
 const action=async(fn,success)=>{try{setBusy(true);await fn();await load();setError(success||'Changes saved successfully.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const incidentAction=(i,a,p={})=>action(async()=>{const id=i.IncidentID;if(a==='verify')await api(`/incident/${id}/verify`,{method:'POST',body:JSON.stringify(p)});else if(a==='reject')await api(`/incident/${id}/reject`,{method:'POST',body:JSON.stringify(p)});else if(a==='assign')await api(`/incident/${id}/assign`,{method:'POST',body:JSON.stringify(p)});else if(a==='status')await api(`/incident/${id}/status`,{method:'PATCH',body:JSON.stringify(p)});else if(a==='note')await api(`/incident/${id}/notes`,{method:'POST',body:JSON.stringify(p)});});
 const tabs=[['overview','Overview','📊'],['incidents','Incidents','🚨'],['map','Live map','🗺️'],['response','Response','👥'],['resources','Resources','📦'],['communications','Communications','📢']];
 const activeIncidents=(data?.incidents||[]).filter(i=>!['Resolved','Expired','Rejected'].includes(i.Status));
 if(adminOnly&&!isAdmin)return <div className="ops-shell"><div className="ops-card"><h2>Admin access required</h2></div></div>;
 return <div className="ops-shell">
  <div className="ops-title"><div><span className="ops-eyebrow">RESPONSE CONTROL CENTRE</span><h1>Operations Centre</h1><p>One workspace for incidents, teams, resources and public response communications across India.</p></div><button className="sos-btn" onClick={sos} disabled={busy}>🚨 Emergency SOS</button></div>
  {error&&<div className="ops-feedback">{error}</div>}
  {data&&<div className="stat-grid">{[['Active Incidents',data.stats.activeIncidents],['People Affected',data.stats.peopleAffected],['Volunteers',data.stats.volunteers],['Communities',data.stats.communities],['Resource Units',data.stats.resourceUnits],['Help Centres',data.stats.centers]].map(x=><div className="stat-card" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div>}
  <div className="ops-tabs" role="tablist">{tabs.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{icon}<span>{label}</span></button>)}</div>
  <div className="ops-content">
   {tab==='overview'&&<div className="ops-section-grid"><section className="ops-card ops-hero-card"><div><span className="mini-label">TODAY'S RESPONSE</span><h2>Keep the response focused.</h2><p>Use the sections above to move from incoming reports to verified incidents, coordinated teams and public updates.</p><div className="quick-actions"><button onClick={()=>setTab('incidents')}>Review incidents <span>→</span></button><button onClick={()=>setTab('map')}>Open live map <span>→</span></button>{isAdmin&&<button onClick={()=>setTab('communications')}>Publish update <span>→</span></button>}</div></div></section><section className="ops-card"><h2>Recent activity</h2>{(data?.announcements||[]).slice(0,4).map(a=><div className="activity-item" key={a.AnnouncementID}><b>{a.Title||'Response update'}</b><span>{a.Content}</span></div>)}{!data?.announcements?.length&&<div className="empty-state">No recent response updates.</div>}</section></div>}
   {tab==='incidents'&&<div className="ops-card"><div className="section-head"><div><span className="mini-label">INCIDENT QUEUE</span><h2>Active Incident Workflow</h2><p>Review reports and move verified incidents through the response lifecycle.</p></div><button className="primary-btn" onClick={()=>setTab('report')}>+ Report incident</button></div>{!canManage&&<p className="workflow-hint">Your account can report incidents. Administrators and responders can verify and assign response teams.</p>}<div className="incident-list">{activeIncidents.length?activeIncidents.map(i=><div className="incident-row" key={i.IncidentID}><button type="button" className="incident-summary" onClick={()=>setExpandedId(expandedId===i.IncidentID?null:i.IncidentID)}><span><b>#{i.IncidentID}</b> {i.IncidentType}</span><span className={`priority-badge priority-${(i.Priority||'medium').toLowerCase()}`}>{i.Priority||i.Urgency}</span><span>{i.Status}</span><span className="muted">{i.IncidentLocation||`Location ${i.LocationID}`}</span><span>⌄</span></button>{expandedId===i.IncidentID&&<IncidentWorkflow incident={i} canManage={canManage} users={teamUsers} onAction={(a,p)=>incidentAction(i,a,p)}/>}</div>):<div className="empty-state">No active incidents in the workflow queue.</div>}</div></div>}
   {tab==='report'&&<section className="ops-card form-card"><div className="section-head"><div><span className="mini-label">NEW REPORT</span><h2>Report an incident</h2><p>Provide clear, useful information. You can update the report later through the response workflow.</p></div></div><form className="modern-form" onSubmit={submitIncident}><div className="form-grid-2"><label><span>Incident type</span><select value={incident.IncidentType} onChange={e=>setIncident({...incident,IncidentType:e.target.value})}>{['Flood','Earthquake','Fire','Cyclone','Landslide','Drought','Heatwave','Accident','Medical Emergency','Others'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Priority</span><select value={incident.Priority} onChange={e=>setIncident({...incident,Priority:e.target.value})}><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></label></div><label><span>Location or landmark</span><input placeholder="e.g. Near Raipur Railway Station" value={incident.Address} onChange={e=>setIncident({...incident,Address:e.target.value})} required/><small>Use a recognizable place name instead of entering technical coordinates when possible.</small></label><label><span>What is happening?</span><textarea rows="5" placeholder="Describe the situation, visible risks and immediate needs..." value={incident.Description} onChange={e=>setIncident({...incident,Description:e.target.value})} required/></label><div className="form-grid-2"><label><span>Latitude</span><input type="number" step="any" value={incident.Latitude} onChange={e=>setIncident({...incident,Latitude:e.target.value})} required/></label><label><span>Longitude</span><input type="number" step="any" value={incident.Longitude} onChange={e=>setIncident({...incident,Longitude:e.target.value})} required/></label></div><label><span>Approximate people affected <em>Optional</em></span><input type="number" min="0" placeholder="0" value={incident.ApproximateaffectedCount} onChange={e=>setIncident({...incident,ApproximateaffectedCount:e.target.value})}/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setTab('overview')}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Submitting…':'Submit incident report'}</button></div></form></section>}
   {tab==='map'&&<section className="ops-card"><div className="section-head"><div><span className="mini-label">LIVE SITUATION MAP</span><h2>India incident & relief map</h2><p>Explore current response locations and nearby support centres.</p></div></div><div className="ops-map large"><MapContainer center={center} zoom={5} minZoom={4} maxZoom={13} maxBounds={bounds} maxBoundsViscosity={1}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{locations.map((x,i)=><Marker key={i} position={x.position}><Popup>{x.popupText}</Popup></Marker>)}</MapContainer></div></section>}
   {tab==='response'&&<div className="ops-section-grid"><section className="ops-card"><div className="section-head"><div><span className="mini-label">VOLUNTEERS</span><h2>Response tasks</h2></div></div>{isAdmin&&<form className="modern-form compact-form" onSubmit={e=>{e.preventDefault();action(async()=>{await api('/api/tasks',{method:'POST',body:JSON.stringify(task)});setTask({Description:'',AssignedTo:'',IncidentID:''})},'Task assigned successfully.')}}><label><span>Task description</span><input value={task.Description} onChange={e=>setTask({...task,Description:e.target.value})} placeholder="e.g. Deliver water to shelter" required/></label><div className="form-grid-2"><label><span>Volunteer user ID</span><input type="number" value={task.AssignedTo} onChange={e=>setTask({...task,AssignedTo:e.target.value})} required/></label><label><span>Incident ID</span><input type="number" value={task.IncidentID} onChange={e=>setTask({...task,IncidentID:e.target.value})} required/></label></div><button className="primary-btn">Assign response task</button></form>}<div className="task-list">{tasks.map(t=><div className="task" key={t.TaskID}><b>#{t.TaskID}</b><span>{t.Description}</span><small>Incident #{t.IncidentID} · {t.Status}</small>{t.AssignedTo===user?.UserID&&!['Completed'].includes(t.Status)&&<button onClick={()=>action(async()=>api(`/api/tasks/${t.TaskID}`,{method:'PATCH',body:JSON.stringify({Status:t.Status==='Assigned'?'Running':'Completed'})}),'Task status updated.')}>{t.Status==='Assigned'?'Start':'Complete'}</button>}</div>)}</div></section><section className="ops-card"><h2>My notifications</h2>{notifs.length?<div className="notification-stack">{notifs.map(n=><div className="activity-item" key={n.NotificationID}><b>{n.Title}</b><span>{n.Message}</span></div>)}</div>:<div className="empty-state">You're all caught up.</div>}</section></div>}
   {tab==='resources'&&<div className="ops-section-grid"><section className="ops-card"><div className="section-head"><div><span className="mini-label">SUPPLY</span><h2>Resource inventory</h2></div></div><div className="table-wrap modern-table"><table><thead><tr><th>Resource</th><th>Available</th><th>Status</th></tr></thead><tbody>{resources.map(r=><tr key={r.ResourceID}><td><b>{r.Name}</b><small>{r.QuantityType}</small></td><td>{r.Quantity}</td><td><span className="status-pill">{r.Status}</span></td></tr>)}</tbody></table></div></section><section className="ops-card"><span className="mini-label">ALLOCATION</span><h2>Send resources</h2>{isAdmin?<form className="modern-form" onSubmit={e=>{e.preventDefault();action(async()=>{await api(`/api/resources/${allocation.ResourceID}/allocate`,{method:'POST',body:JSON.stringify({IncidentID:Number(allocation.IncidentID),Quantity:Number(allocation.Quantity)})});setAllocation({ResourceID:'',IncidentID:'',Quantity:''})},'Resource allocated successfully.')}}><label><span>Resource</span><select value={allocation.ResourceID} onChange={e=>setAllocation({...allocation,ResourceID:e.target.value})} required><option value="">Choose a resource</option>{resources.map(r=><option key={r.ResourceID} value={r.ResourceID}>{r.Name} · {r.Quantity} {r.QuantityType}</option>)}</select></label><label><span>Incident ID</span><input type="number" value={allocation.IncidentID} onChange={e=>setAllocation({...allocation,IncidentID:e.target.value})} required/></label><label><span>Quantity</span><input type="number" min="1" value={allocation.Quantity} onChange={e=>setAllocation({...allocation,Quantity:e.target.value})} required/></label><button className="primary-btn">Allocate resource</button></form>:<div className="empty-state">Resource allocation is available to administrators.</div>}</section></div>}
   {tab==='communications'&&<div className="ops-section-grid"><section className="ops-card form-card"><span className="mini-label">PUBLIC UPDATE</span><h2>Publish an announcement</h2>{isAdmin?<form className="modern-form" onSubmit={e=>{e.preventDefault();action(async()=>{await api('/api/announcements',{method:'POST',body:JSON.stringify(announcement)});setAnnouncement({Content:'',Urgency:'medium',CommunityID:''})},'Announcement published successfully.')}}><label><span>Message</span><textarea rows="6" value={announcement.Content} onChange={e=>setAnnouncement({...announcement,Content:e.target.value})} placeholder="Write a clear, verified response update..." required/></label><div className="form-grid-2"><label><span>Priority</span><select value={announcement.Urgency} onChange={e=>setAnnouncement({...announcement,Urgency:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label><span>Community ID <em>Optional</em></span><input type="number" value={announcement.CommunityID} onChange={e=>setAnnouncement({...announcement,CommunityID:e.target.value})} placeholder="Blank = all communities"/></label></div><button className="primary-btn">Publish official update</button></form>:<div className="empty-state">Only administrators can publish official announcements.</div>}</section><section className="ops-card"><span className="mini-label">RECENT UPDATES</span><h2>Announcements</h2>{(data?.announcements||[]).map(a=><div className="notice" key={a.AnnouncementID}><b>{a.Urgency?.toUpperCase()}</b><strong>{a.Title||'Response update'}</strong><p>{a.Content}</p></div>)}{!data?.announcements?.length&&<div className="empty-state">No announcements yet.</div>}</section></div>}
  </div>
 </div>
}
